### ISSUE TITLE
Output format is wrong

### ISSUE THREAD

**Issue by joepie91** [compwright/exif-geojson#6]
This module produces the following output:

```json
{
	"geometry": {
		"type": "point",
		"coordinates": [5.360446916666667, 51.72327802777778, 0]
	}
}
```

... but correct GeoJSON would need to look like this, instead:

```json
{
	"type": "Point",
	"coordinates": [5.360446916666667, 51.72327802777778, 0]
}
```

Verified through https://geojsonlint.com/.

Edit: Apparently the `geometry` key *is* correct for the top-level structure despite what the linter said, so that would leave the type capitalization as the bug here.

Upon further experimentation, it seems that eg. OpenStreetMap's iD editor will accept the following as valid GeoJSON:

```json
{
	"type": "Feature",
	"geometry": {
		"type": "Point",
		"coordinates": [5.360446916666667, 51.72327802777778, 0]
	}
}
```

**Comment by compwright** [comment]
@joepie91 thanks for reporting this! Fixed in v1.1.1
